### ISSUE TITLE
NPC NAMES AND FACES

### ISSUE THREAD

**Issue by RubiLeonard** [MultiTheFranky/rtf-42nd#187]
Que al meter la misión se mantenga los nombres, cara y complementos de los NPCs. Al menos los nombres ya que con las caras y algunos añadidos (las barbas) me he fijado que dependen del mod de donde vienen.

**Comment by MultiTheFranky** [comment]
This is based a lot on other mods as some of them do some randomize on post init. With the change that I've made, it should not affect our units. This needs to be tested deeply as it can't be tested locally (or at least I didn't have the issue)
