### ISSUE TITLE
INGAME EVENT CARD SYSTEM

### ISSUE THREAD

**Issue by RubiLeonard** [MultiTheFranky/rtf-42nd#20]
Necesito una función/modulo simple (para tontos) y rápida que muestre INGAME a todos la carta que usa el lider. Debe ser activable para que se le muestre a todos los players en partida desde el ZEUS. Colocación y tamaño igual al usada con las cartas de baraja.

**Comment by MultiTheFranky** [comment]
Necesito una lista con las cartas y las imágenes que tienen que salir.
