### ISSUE TITLE
TROOPS SETUP

### ISSUE THREAD

**Issue by RubiLeonard** [MultiTheFranky/rtf-42nd#98]
NOMBRE: RANGER RIFLEMAN
CLASS NAME: rtf42_units_Ranger_Rifleman

`[[["rhs_weap_m4a1_carryhandle","","","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],[],["rtf42_uniforms_MC",[["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1],["rtf42_items_Cards",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["milgp_v_mmac_light_rgr",[["rhsusf_acc_wmx_bk",1],["ACE_IR_Strobe_Item",1],["ACE_quikclot",1],["ACE_packingBandage",1],["SmokeShell",2,1],["Chemlight_green",2,1],["rhs_mag_m67",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["B_AssaultPack_rgr",[["ACE_splint",1],["ACE_packingBandage",4],["ACE_quikclot",9],["ACE_EntrenchingTool",1],["ACE_CableTie",10],["rhs_mag_m67",1,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["rhs_mag_mk84",2,1]]],"CUP_H_OpsCore_Covered_MCAM","rhsusf_oakley_goggles_clr",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
PARAMEDIC

`[[["rhs_weap_m4_carryhandle","","rhsusf_acc_wmx_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_grip2"],[],[],["rtf42_uniforms_MC",[["ACE_EarPlugs",1],["rtf42_items_Cards",1]]],["milgp_v_mmac_medic_rgr",[["ACE_IR_Strobe_Item",1],["HandGrenade",1,1],["SmokeShell",2,1],["Chemlight_green",2,1],["SmokeShellGreen",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,30]]],["milgp_b_patrol_01_rgr",[["ACE_packingBandage",20],["ACE_quikclot",25],["ACE_elasticBandage",10],["ACE_salineIV_500",5],["ACE_salineIV_250",5],["ACE_splint",10],["ACE_tourniquet",10],["ACE_morphine",15],["ACE_epinephrine",10],["ACE_EntrenchingTool",1]]],"rtf42_helmets_MC","rhsusf_oakley_goggles_clr",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
NOMBRE: RANGER SAPPER
CLASS NAME: rtf_units_Ranger_Sapper

`[[["rhs_weap_m4a1_carryhandle","","","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],[],["rtf42_uniforms_MC",[["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1],["rtf42_items_Cards",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["milgp_v_mmac_light_rgr",[["rhsusf_acc_wmx_bk",1],["ACE_IR_Strobe_Item",1],["ACE_quikclot",1],["ACE_packingBandage",1],["SmokeShell",2,1],["Chemlight_green",2,1],["rhs_mag_m67",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["B_AssaultPack_rgr",[["ACE_splint",1],["ACE_packingBandage",4],["ACE_quikclot",9],["ACE_EntrenchingTool",1],["ACE_DefusalKit",1],["ACE_M26_Clacker",1],["ACE_wirecutter",1],["ACE_CableTie",10],["rhs_mag_m67",1,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["rhs_mag_mk84",2,1],["DemoCharge_Remote_Mag",3,1]]],"rtf42_helmets_MC","rhsusf_oakley_goggles_clr",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
NOMBRE: RANGER AT SPECIALIST
CLASS NAME: rtf_units_Ranger_AT

`[[["rhs_weap_m4a1_carryhandle","","rhsusf_acc_wmx_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],["rhs_weap_M136_hedp","","","",[],[],""],[],["rtf42_uniforms_MCS",[["rtf42_items_Cards",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_tourniquet",1],["ACE_splint",1],["ACE_packingBandage",5],["ACE_quikclot",10]]],["milgp_v_mmac_hgunner_rgr",[["ACE_IR_Strobe_Item",1],["HandGrenade",2,1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["Chemlight_green",2,1],["SmokeShellRed",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,30]]],["B_Kitbag_rgr",[["ACE_EntrenchingTool",1],["ACE_EarPlugs",1]]],"rtf42_helmets_MC","rhsusf_oakley_goggles_clr",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
NOMBRE: RANGER RTO
CLASS NAME: rtf_units_Ranger_RTO

`[[["rhs_weap_m4a1_carryhandle","","","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],[],["rtf42_uniforms_MCS",[["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1],["rtf42_items_Cards",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["milgp_v_mmac_teamleader_rgr",[["rhsusf_acc_wmx_bk",1],["ACE_IR_Strobe_Item",1],["ACE_quikclot",5],["ACE_packingBandage",1],["SmokeShell",2,1],["Chemlight_green",2,1],["rhs_mag_m67",1,1],["SmokeShellBlue",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["B_FieldPack_khk",[["ACE_splint",1],["ACE_packingBandage",4],["ACE_quikclot",5],["ACE_EntrenchingTool",1],["ACE_CableTie",10],["ACRE_PRC117F",1],["rhs_mag_m67",1,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["rhs_mag_mk84",2,1]]],"CUP_H_OpsCore_Covered_MCAM","rhsusf_oakley_goggles_clr",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
NOMBRE: RANGER TEAM LEADER
CLASS NAME: rtf_units_Ranger_TL

`[[["rhs_weap_m4a1_carryhandle","","","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],[],["rtf42_uniforms_MC",[["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1],["rtf42_items_Cards",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["milgp_v_mmac_teamleader_rgr",[["rhsusf_acc_wmx_bk",1],["ACE_IR_Strobe_Item",1],["ACE_quikclot",1],["ACE_packingBandage",1],["SmokeShell",2,1],["Chemlight_green",2,1],["rhs_mag_m67",1,1],["SmokeShellOrange",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["B_AssaultPack_rgr",[["ACE_splint",1],["ACE_packingBandage",4],["ACE_quikclot",9],["ACE_EntrenchingTool",1],["ACE_SpraypaintBlue",1],["ACE_CableTie",10],["rhs_mag_m67",1,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["rhs_mag_mk84",2,1]]],"CUP_H_OpsCore_Spray_US_SF","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
NOMBRE: RANGER SQUAD LEADER
CLASS NAME: rtf_units_Ranger_SL

`[[["rhs_weap_m4a1_carryhandle","","","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rtf42_uniforms_MCS",[["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1],["rtf42_items_Cards",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["milgp_v_marciras_teamleader_RGR",[["rhsusf_acc_wmx_bk",1],["ACE_IR_Strobe_Item",1],["ACE_quikclot",1],["ACE_packingBandage",1],["SmokeShell",2,1],["Chemlight_green",2,1],["rhs_mag_m67",1,1],["SmokeShellOrange",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["B_AssaultPack_rgr",[["ACE_splint",1],["ACE_packingBandage",4],["ACE_quikclot",9],["ACE_EntrenchingTool",1],["ACE_SpraypaintBlue",1],["ACRE_PRC152",1],["ACE_MapTools",1],["ACE_Flashlight_MX991",1],["ACE_CableTie",10],["rhs_mag_m67",1,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["rhs_mag_mk84",2,1],["Laserbatteries",2,1]]],"rhsusf_mich_bare_norotos_alt","rhsusf_oakley_goggles_clr",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by RubiLeonard** [comment]
NOMBRE: RANGER OFFICER
CLASS NAME: rtf_units_Ranger_Officer

`[[["rhs_weap_m4a1_carryhandle","","","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rtf42_uniforms_MCS",[["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1],["rtf42_items_Cards",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["milgp_v_marciras_teamleader_belt_RGR",[["rhsusf_acc_wmx_bk",1],["ACE_IR_Strobe_Item",1],["ACE_quikclot",1],["ACE_packingBandage",1],["SmokeShell",2,1],["Chemlight_green",2,1],["rhs_mag_m67",1,1],["SmokeShellOrange",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["B_AssaultPack_rgr",[["ACE_splint",1],["ACE_packingBandage",4],["ACE_quikclot",9],["ACE_EntrenchingTool",1],["ACE_SpraypaintBlue",1],["ACRE_PRC152",1],["ACE_MapTools",1],["ACE_Flashlight_MX991",1],["ACE_CableTie",5],["rhs_mag_m67",1,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["rhs_mag_mk84",2,1],["Laserbatteries",2,1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Yellow",1,1],["SmokeShellBlue",2,1]]],"rhsusf_mich_bare_norotos_alt_tan","rhsusf_oakley_goggles_clr",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","ItemRadio","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]],[]]`

**Comment by MultiTheFranky** [comment]
Done
